"""Exception types and error factories used throughout Ghostbytes."""

from datetime import datetime

INTERNAL_ERROR = "INTERNAL_ERROR"
USAGE_ERROR = "USAGE_ERROR"
INCORRECT_KEY_ERROR = "INCORRECT_KEY"


class GhostBytesError(Exception):
    """Base exception carrying a user-facing message and optional heading."""

    def __init__(self, message, heading=None):
        super().__init__(message)
        self.heading = heading
        self.message = message

    def __str__(self):
        now = datetime.now().replace(microsecond=0).isoformat()
        heading = self.__class__.__name__.removesuffix("Error") + " Error"
        if self.heading is not None:
            heading += f" ({self.heading})"
        return f"[{now}] {heading}: {self.message}"


class CryptoError(GhostBytesError):
    """Error raised for cryptographic operation failures."""


class GeneralError(GhostBytesError):
    """Error raised for invalid usage or general operation failures."""


# Cryptographic operation errors.
def decryption_key_incorrect(): return CryptoError("Decryption key incorrect!")


def data_integrity_check_failed(): return CryptoError(
    "Data integrity check failed. The data may have been modified or corrupted.")


def keyfile_passphrase_incorrect(): return CryptoError(
    "Passphrase for RSA private key incorrect!")


def keyfile_cannot_crypt(operation): return CryptoError(
    f"Provided RSA key cannot {operation}")


def invalid_keyfile(): return CryptoError(
    "Invalid keyfile. Use a public/private key pair generated by Ghostbytes or an equivalent tool.")


def unsupported_keyfile(): return CryptoError(
    "Unsupported keyfile. Use a keyfile generated by a supported algorithm.")


def envelope_too_small(): return CryptoError(
    "Failed to extract encryption envelope. The file is too small to contain encrypted data.",
    USAGE_ERROR)


def rsa_message_too_big(): return CryptoError(
    "Failed to encrypt RSA message. The message exceeds the maximum size supported by the key.")


def algorithm_not_supported(): return CryptoError(
    "Algorithm not supported", INTERNAL_ERROR)


def store_iv_choice_mismatch(): return CryptoError(
    "STORE_IV must be either `append` or `prepend`", USAGE_ERROR)
def aes_envelope_extraction_failed(): return CryptoError(
    "AES envelope extraction failed", INTERNAL_ERROR)


def hash_not_supported(): return CryptoError("Hash not supported", USAGE_ERROR)


def rsa_public_exponent_not_prime(): return CryptoError(
    "Public exponent is not a prime number", USAGE_ERROR)


def unsupported_mlkem_key(): return CryptoError(
    "The selected key is not a supported ML-KEM-768 or ML-KEM-1024 key.",
    USAGE_ERROR)


def text_not_in_bytes(): return TypeError(
    "Ciphertext / plaintext must be in Bytes form")

# Input and configuration errors.


def parameter_not_exist(name): return GeneralError(
    f"Parameter name `{name}` must exist.", USAGE_ERROR)


invalid_argument = lambda name, detail="is invalid": GeneralError(
    f"Parameter `{name}` {detail}.", USAGE_ERROR)


def invalid_configuration(detail): return GeneralError(
    f"Invalid Ghostbytes configuration: {detail}", USAGE_ERROR)


def invalid_configuration_type(): return GeneralError(
    "Configuration must be an instance of `CryptoConfig`.", USAGE_ERROR)


def invalid_mode(mode): return GeneralError(
    f"Unsupported batch mode `{mode}`. Use `encrypt` or `decrypt`.", USAGE_ERROR)


def invalid_random_length(): return GeneralError(
    "Random byte length must be a non-negative integer.", USAGE_ERROR)


def invalid_repeat(): return GeneralError(
    "Shred repeat count must be at least 1.", USAGE_ERROR)


def invalid_pattern(): return GeneralError(
    "Overwrite pattern cannot be empty.", USAGE_ERROR)


def key_encoding_not_found(): return GeneralError(
    "Key encoding not found", USAGE_ERROR)

# File and system errors.


def io_error(operation): return GeneralError(
    f"Unable to {operation}.", INTERNAL_ERROR)


def temporary_write_failed(): return GeneralError(
    "Unable to write temporary wipe data.", INTERNAL_ERROR)


def file_not_found(): return GeneralError(
    "Filename specified cannot be found", USAGE_ERROR)


def not_a_file(): return GeneralError(
    "The selected filename is not a file.", USAGE_ERROR)


def shred_option_not_supported(): return GeneralError(
    "Shred option not supported", USAGE_ERROR)


def chunk_size_invalid(): return GeneralError(
    "Chunk size in shred functions must be greater than zero", USAGE_ERROR)


def partition_not_found(): return GeneralError(
    "Disk partition not found!", INTERNAL_ERROR)


def temporary_filename_unavailable(): return GeneralError(
    "Failed to generate a random temporary file for shred operations", INTERNAL_ERROR)

# Randomness and key-management errors.


def random_function_not_supported(): return CryptoError(
    "Random function not supported", USAGE_ERROR)


def unix_only_function(function): return GeneralError(
    f"{function} is only available on Unix-like systems.", USAGE_ERROR
)
