"""
random.py

This modules provides a unified interface for generating random bytes
from different libraries, operating sytems, and cryptographic sources.

Supported sources are listed in crypto/config.py

It also provides a helper for using the Unix ``dd`` command to write random
data directly to a file.
"""

import subprocess as _subprocess
from secrets import token_bytes as _secrets_randbytes
from random import randbytes as _random_randbytes
from os import urandom as _os_urandom
from os import name as _os_name

from Crypto.Random import get_random_bytes as _cryptodome_randbytes
from ghostbytes.crypto.config import AVAIL_RANDOM_STR as _AVAIL_RANDOM_STR
from ghostbytes.error import invalid_random_length as _invalid_random_length
from ghostbytes.error import random_function_not_supported as _random_function_not_supported
from ghostbytes.error import unix_only_function as _unix_only_function

def random(algorithm, length):
    """
    Generate random bytes using the selected random-data sources (algorithms)

    Args:
        algorithm: Name of the random-data sources. Support values are:
            - ``"os.urandom"``
            - ``"cryptodome_random"``
            - ``"secrets_random"``
            - ``"random lib (python)"``
            - ``"/dev/urandom (*nux only)"``
            - ``"/dev/random (*nux only)"``
        length: Number of random bytes to generate. Must be a non-negative integer
    
    Returns:
        bytes: Randomly generated bytes of length ``length``
    
    Raises:
        invalid_random_length: if ``length`` is not an integer or is negative.
        random_function_not_supported: if ``algorithm`` is not supported
        unix_only_function: if a unix-only sources is requested on a non-POSIX OS.
        subprocess.CalledProcessError: if a Unix device source fails while being read.
    """
    if not isinstance(length, int) or length < 0:
        raise _invalid_random_length()
    if algorithm not in _AVAIL_RANDOM_STR:
        raise _random_function_not_supported()
    if _os_name != "posix" and "(*nux only)" in algorithm:
        raise _unix_only_function(algorithm)

    match algorithm:
        case "os.urandom":
            return _os_urandom(length)
        case "cryptodome_random":
            return _cryptodome_randbytes(length)
        case "secrets_random":
            return _secrets_randbytes(length)
        case "random lib (python)":
            return _random_randbytes(length)
        case "/dev/urandom (*nux only)":
            return _subprocess.run(
                ["head","-c",str(length),"/dev/urandom"],
                stdout=_subprocess.PIPE,
                stderr=_subprocess.PIPE,
                check=True
            ).stdout
        case "/dev/random (*nux only)":
            return _subprocess.run(
                ["head","-c",str(length),"/dev/random"],
                stdout=_subprocess.PIPE,
                stderr=_subprocess.PIPE,
                check=True
            ).stdout
        case _:
            raise _random_function_not_supported()

def dd_random_to_file(is_secure,outfile,bs,count):
    """
    Write random data to a file using the Unix ``dd`` command

    The function copies ``bs * count`` bytes from
    ``/dev/urandom`` or ``/dev/random`` to ``outfile``. 
    
    Args:
        is_secure: select the random source.
            ``True`` uses ``/dev/urandom``; ``False`` uses ``/dev/random``
        outfile: path of the output file
        bs: number of bytes per block passed to ``dd``
        count: number of blocks to write

    Returns:
        subprocess.CompletedProcess: The completed ``dd`` process.
    
    Raises:
        unix_only_function: if called on a non-POSIX OS.
        subprocess.CalledProcessError: if the ``dd`` command fails.
    """
    if _os_name != 'posix':
        raise _unix_only_function("dd random sources")
    if is_secure:
        return _subprocess.run(
            ["dd","if=/dev/urandom",f"of={outfile}",
             f"bs={str(bs)}",f"count={str(count)}","status=none"],
            stdout=_subprocess.PIPE,
            stderr=_subprocess.PIPE,
            check=True
        )
    return _subprocess.run(
        ["dd","if=/dev/random",f"of={outfile}",
            f"bs={str(bs)}",f"count={str(count)}","status=none"],
        stdout=_subprocess.PIPE,
        stderr=_subprocess.PIPE,
        check=True
    )
